import { PackagingTemplate, ZoneGroup } from "./types";

export const templates: PackagingTemplate[] = [
  {
    id: "tuck-end-box",
    name: "Tuck End Box",
    category: "boxes",
    description: "Classic tuck end packaging box — ideal for retail products",
    surfaces: ["front", "back", "left", "right", "top"],
    defaultColor: "#ffffff",
    thumbnail: "/thumbnails/box.png",
  },
  {
    id: "bottle",
    name: "Plastic Bottle",
    category: "bottles",
    description: "Standard cylindrical bottle with label wrap",
    surfaces: ["body", "cap"],
    defaultColor: "#ffffff",
    thumbnail: "/thumbnails/bottle.png",
  },
  {
    id: "beverage-can",
    name: "Beverage Can",
    category: "cans",
    description: "Standard aluminium beverage can",
    surfaces: ["body"],
    defaultColor: "#c0c0c0",
    thumbnail: "/thumbnails/can.png",
  },
  {
    id: "stand-up-pouch",
    name: "Stand-Up Pouch",
    category: "pouches",
    description: "Flexible stand-up pouch with front and back panels",
    surfaces: ["front", "back"],
    defaultColor: "#ffffff",
    thumbnail: "/thumbnails/pouch.png",
  },
  {
    id: "cosmetic-tube",
    name: "Cosmetic Tube",
    category: "tubes",
    description: "Squeezable cosmetic tube with flip cap",
    surfaces: ["body", "cap"],
    defaultColor: "#ffffff",
    thumbnail: "/thumbnails/tube.png",
  },
  {
    id: "coffee-cup",
    name: "Coffee Cup",
    category: "cups",
    description: "Paper coffee cup with sleeve area",
    surfaces: ["body", "sleeve"],
    defaultColor: "#ffffff",
    thumbnail: "/thumbnails/cup.png",
  },
  {
    id: "car-sedan",
    name: "Dodge Charger",
    category: "vehicles",
    description: "2013 Dodge Charger SRT8 — full body wrap",
    surfaces: ["body"],
    defaultColor: "#ffffff",
    thumbnail: "/thumbnails/car-sedan.png",
  },
  {
    id: "car-van",
    name: "Dodge Challenger",
    category: "vehicles",
    description: "Dodge Challenger SRT Hellcat — full body wrap",
    surfaces: ["body"],
    defaultColor: "#ffffff",
    thumbnail: "/thumbnails/car-van.png",
  },
  {
    id: "porsche-911",
    name: "Porsche 911",
    category: "vehicles",
    description: "Porsche 911 Targa 4S — full body wrap with panel canvas zones",
    surfaces: ["body"],
    canvasZones: [
      { id: "hood",            label: "Hood (Front Lid)" },
      { id: "engine_lid",      label: "Engine Lid" },
      { id: "roof",            label: "Roof" },
      { id: "bumper_front",    label: "Front Bumper" },
      { id: "bumper_rear",     label: "Rear Bumper" },
      { id: "fender_fl",       label: "Front Left Fender" },
      { id: "fender_fr",       label: "Front Right Fender" },
      { id: "rear_quarter_l",  label: "Rear Left Quarter" },
      { id: "rear_quarter_r",  label: "Rear Right Quarter" },
      { id: "door_l",          label: "Left Door" },
      { id: "door_r",          label: "Right Door" },
      { id: "rocker_l",        label: "Left Rocker" },
      { id: "rocker_r",        label: "Right Rocker" },
      { id: "body_misc",       label: "Body (Other)" },
      { id: "trim",            label: "Body Trim" },
    ],
    zoneGroups: [
      { id: "racing_stripe",  label: "Racing Stripe",    zoneIds: ["hood", "roof", "engine_lid"],                              isPredefined: true },
      { id: "full_left",      label: "Full Left Side",   zoneIds: ["fender_fl", "door_l", "rear_quarter_l", "rocker_l"],       isPredefined: true },
      { id: "full_right",     label: "Full Right Side",  zoneIds: ["fender_fr", "door_r", "rear_quarter_r", "rocker_r"],       isPredefined: true },
      { id: "front_end",      label: "Front End",        zoneIds: ["bumper_front", "hood", "fender_fl", "fender_fr"],          isPredefined: true },
      { id: "both_doors",     label: "Both Doors",       zoneIds: ["door_l", "door_r"],                                        isPredefined: true },
      { id: "both_sides",     label: "Both Sides",       zoneIds: ["fender_fl", "fender_fr", "door_l", "door_r", "rear_quarter_l", "rear_quarter_r", "rocker_l", "rocker_r"], isPredefined: true },
    ] as ZoneGroup[],
    defaultColor: "#ffffff",
    thumbnail: "/thumbnails/car-sedan.png",
  },
  {
    id: "bmw-x5m",
    name: "BMW X5M",
    category: "vehicles",
    description: "2016 BMW X5M — full body wrap with panel canvas zones",
    surfaces: ["body"],
    canvasZones: [
      { id: "hood",         label: "Hood" },
      { id: "roof",         label: "Roof" },
      { id: "trunk",        label: "Trunk" },
      { id: "bumper_front", label: "Front Bumper" },
      { id: "bumper_rear",  label: "Rear Bumper" },
      { id: "fender_fl",    label: "Front Left Fender" },
      { id: "fender_fr",    label: "Front Right Fender" },
      { id: "door_fl",      label: "Front Left Door" },
      { id: "door_fr",      label: "Front Right Door" },
      { id: "door_rl",      label: "Rear Left Door" },
      { id: "door_rr",      label: "Rear Right Door" },
      { id: "rocker_l",     label: "Left Rocker" },
      { id: "rocker_r",     label: "Right Rocker" },
      { id: "body_misc",    label: "Body (Other)" },
      { id: "trim",         label: "Body Trim" },
    ],
    zoneGroups: [
      { id: "racing_stripe", label: "Racing Stripe",   zoneIds: ["hood", "roof", "trunk"],                              isPredefined: true },
      { id: "full_left",     label: "Full Left Side",  zoneIds: ["fender_fl", "door_fl", "door_rl", "rocker_l"],        isPredefined: true },
      { id: "full_right",    label: "Full Right Side", zoneIds: ["fender_fr", "door_fr", "door_rr", "rocker_r"],        isPredefined: true },
      { id: "front_end",     label: "Front End",       zoneIds: ["bumper_front", "hood", "fender_fl", "fender_fr"],     isPredefined: true },
      { id: "all_doors",     label: "All Doors",       zoneIds: ["door_fl", "door_fr", "door_rl", "door_rr"],           isPredefined: true },
      { id: "both_sides",    label: "Both Sides",      zoneIds: ["fender_fl", "fender_fr", "door_fl", "door_fr", "door_rl", "door_rr", "rocker_l", "rocker_r"], isPredefined: true },
    ] as ZoneGroup[],
    defaultColor: "#ffffff",
    thumbnail: "/thumbnails/car-sedan.png",
  },
];

export function getTemplate(id: string): PackagingTemplate | undefined {
  return templates.find((t) => t.id === id);
}

export function getTemplatesByCategory(
  category: string
): PackagingTemplate[] {
  return templates.filter((t) => t.category === category);
}
